# AutoLearnCorrectLLM spec as Python
AUTO_LEARN_CORRECT_LLM = {'canary': {'promotion_after_min': 30,
            'rollback_if': {'drift_over': 0.25,
                            'error_rate_multiplier': 1.5,
                            'latency_p95_ms_over': 300},
            'traffic_percent': 5},
 'decision_table': [{'then': ['tool.propose_model_update',
                              'tool.start_canary',
                              'tool.increase_segment_sampling'],
                     'when': {'drift_score_gt': 0.2, 'risk_score_le': 0.6}},
                    {'then': ['tool.freeze_new_plans',
                              'tool.rollback_last_change',
                              'tool.open_incident'],
                     'when': {'error_rate_spike_x': 1.5}},
                    {'then': ['tool.enable_backpressure',
                              'tool.scale_out_api',
                              'tool.optimize_index_refresh'],
                     'when': {'latency_p95_ms_gt': 250}},
                    {'then': ['tool.local_enforce',
                              'tool.queue_remote_sync',
                              'tool.enter_degraded_state'],
                     'when': {'offline_mode': True}}],
 'memory_rag': {'chunking': {'max_chars': 1200, 'overlap': 120},
                'rank_fusion': {'k': 60, 'method': 'RRF'},
                'retrievers': [{'fields': ['payload.text', 'labels.*'], 'type': 'inverted'},
                               {'dim': 768,
                                'hnsw': {'M': 32, 'ef_search': 128},
                                'index': 'hnsw',
                                'metric': 'cosine',
                                'type': 'vector'},
                               {'granularity': '1m', 'key': 'ts_et', 'type': 'time_series'}],
                'stateless_api': True},
 'meta': {'description': 'Function-calling LLM agent implementing detect→plan→enforce→verify→learn '
                         'with DSRV framing, stateless APIs, scalable indexing (RAG), and offline '
                         'continuity.',
          'generated_at_et': '2025-09-10T20:22:00-04:00',
          'name': 'AutoLearnCorrectLLM',
          'owner_role': 'Atlas Reverse Engineer (ARE)',
          'version': '0.1.0'},
 'model': {'json_mode': True,
           'max_tokens': 2048,
           'model_id': 'llm_function_calling',
           'provider': 'vendor_agnostic',
           'temperature': 0.2,
           'tool_choice': 'auto',
           'top_p': 0.9},
 'monitoring': {'logging': {'audit_channel': 'audit', 'format': 'jsonl'},
                'metrics': ['latency_p95_ms',
                            'throughput_eps',
                            'error_rate',
                            'drift_score',
                            'canary_success'],
                'tracing': {'distributed': True}},
 'offline': {'consistency': {'crdt_log': True, 'merkle_sync': True},
             'degraded_modes': ['read_only', 'local_enforce_with_quorum=1'],
             'enabled': True,
             'store_and_forward': {'flush_policy': 'size_or_interval',
                                   'max_gb': 10,
                                   'spill': 'disk'}},
 'policies': {'backpressure': {'leaky_bucket': {'burst': 200, 'rate_per_min': 600}},
              'budget_guard': {'max_cost_per_event_usd': 0.0005},
              'idempotency': {'header': 'Idempotency-Key', 'required': True},
              'pii_redaction': {'enabled': True, 'strategies': ['mask', 'hash_salted']},
              'rbac': {'default_role': 'reader', 'roles': ['owner', 'controller', 'reader']},
              'risk_gate': {'require_approval_if_high_risk': True, 'risk_score_max': 0.6}},
 'prompts': {'developer': 'You are stateless. Persist state only via tools/stores. Prefer small, '
                          'testable changes. For high-risk actions require APPROVAL. Respect '
                          'decision_table. Use canary first; rollback on thresholds. Keep '
                          'timestamps in ET (ISO 8601 with offset).',
             'system': 'Role: Auto-Learn-and-Correct Controller (ARE). Follow DSRV: '
                       'Observe→Decompose→Recompose→Validate. Single intent: reduce defects and '
                       'latency while preserving safety. Use evidence-first reasoning, cite '
                       'metrics, propose minimal-diff plans, and honor gates (risk ≤ 0.6, budget '
                       'guard on cost/event). Enforce idempotency. Never exfiltrate secrets; '
                       'redact PII. If offline, switch to local enforcement and queue sync. Output '
                       'structured JSON matching tool schemas and policy.',
             'user_template': 'Objective: {{objective}}. Context window keys: '
                              'tenant={{tenant_id}}, ts_et={{ts_et}}. Constraints: '
                              'latency_p95_ms_max={{latency_target}}, '
                              'error_rate_p95_max={{error_target}}.'},
 'tools': [{'description': 'Validate and ingest an Event; dedupe by idempotency key; index into '
                           'stores.',
            'input_schema': {'additionalProperties': False,
                             'properties': {'event_id': {'type': 'string'},
                                            'features': {'type': 'object'},
                                            'idempotency_key': {'type': 'string'},
                                            'labels': {'type': 'object'},
                                            'payload': {'type': 'object'},
                                            'tenant_id': {'type': 'string'},
                                            'ts_et': {'format': 'date-time', 'type': 'string'}},
                             'required': ['event_id', 'tenant_id', 'ts_et', 'payload'],
                             'type': 'object'},
            'name': 'observe_event'},
           {'description': 'Analyze events/metrics to detect errors, drift, and latency hotspots.',
            'input_schema': {'properties': {'signals': {'items': {'enum': ['error_rate',
                                                                           'latency',
                                                                           'drift',
                                                                           'throughput'],
                                                                  'type': 'string'},
                                                        'type': 'array'},
                                            'window_end_et': {'format': 'date-time',
                                                              'type': 'string'},
                                            'window_start_et': {'format': 'date-time',
                                                                'type': 'string'}},
                             'required': ['window_start_et', 'window_end_et'],
                             'type': 'object'},
            'name': 'detect_issues'},
           {'description': 'Generate a minimal-diff plan to reduce error/latency or address drift.',
            'input_schema': {'properties': {'context': {'type': 'object'},
                                            'objective': {'enum': ['reduce_error',
                                                                   'reduce_latency',
                                                                   'increase_accuracy'],
                                                          'type': 'string'},
                                            'risk_budget': {'maximum': 1,
                                                            'minimum': 0,
                                                            'type': 'number'}},
                             'required': ['objective', 'context'],
                             'type': 'object'},
            'name': 'plan_solutions',
            'output_schema': {'properties': {'actions': {'items': {'type': 'object'},
                                                         'type': 'array'},
                                             'plan_id': {'type': 'string'},
                                             'risk_score': {'maximum': 1,
                                                            'minimum': 0,
                                                            'type': 'number'}},
                              'required': ['plan_id', 'actions', 'risk_score'],
                              'type': 'object'}},
           {'description': 'Escalate plan for human approval when risk or policy requires it.',
            'input_schema': {'properties': {'justification': {'type': 'string'},
                                            'plan_id': {'type': 'string'},
                                            'risk_score': {'type': 'number'}},
                             'required': ['plan_id', 'risk_score', 'justification'],
                             'type': 'object'},
            'name': 'request_approval'},
           {'description': 'Apply actions idempotently with canary and rollback hooks.',
            'input_schema': {'properties': {'actions': {'items': {'type': 'object'},
                                                        'type': 'array'},
                                            'canary_percent': {'maximum': 50,
                                                               'minimum': 1,
                                                               'type': 'integer'},
                                            'idempotency_key': {'type': 'string'},
                                            'plan_id': {'type': 'string'}},
                             'required': ['plan_id',
                                          'actions',
                                          'idempotency_key',
                                          'canary_percent'],
                             'type': 'object'},
            'name': 'enforce_actions'},
           {'description': 'Measure post-enforcement metrics vs baseline; decide promote/rollback.',
            'input_schema': {'properties': {'evaluation_window_min': {'minimum': 5,
                                                                      'type': 'integer'},
                                            'plan_id': {'type': 'string'},
                                            'success_criteria': {'properties': {'auprc_delta_min': {'type': 'number'},
                                                                                'latency_p95_ms_max': {'type': 'integer'}},
                                                                 'type': 'object'}},
                             'required': ['plan_id', 'evaluation_window_min'],
                             'type': 'object'},
            'name': 'verify_outcome'},
           {'description': 'Apply safe online/offline learning if gates pass; update '
                           'indexes/models.',
            'input_schema': {'properties': {'drift_score': {'type': 'number'},
                                            'method': {'enum': ['contextual_bandit',
                                                                'incremental_gradient',
                                                                'offline_retrain'],
                                                       'type': 'string'},
                                            'p_value': {'type': 'number'},
                                            'plan_id': {'type': 'string'}},
                             'required': ['plan_id', 'method'],
                             'type': 'object'},
            'name': 'learn_update'},
           {'description': 'Return health, drift, errors, and offline/online mode.',
            'input_schema': {'properties': {'detail': {'type': 'boolean'}}, 'type': 'object'},
            'name': 'status'}]}

if __name__ == "__main__":
    import json, sys
    json.dump(AUTO_LEARN_CORRECT_LLM, sys.stdout, indent=2)
    sys.stdout.write("\n")
